services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "7071:7070"
    depends_on:
      - postgres
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://postgres:5432/students_management
      - SPRING_DATASOURCE_USERNAME=${USERNAME}
      - SPRING_DATASOURCE_PASSWORD=${PASSWORD}
      - SPRING_JPA_HIBERNATE_DDL_AUTO=update

  postgres:
    image: postgres:latest
    environment:
      - POSTGRES_DB=students_management
      - POSTGRES_USER=${USERNAME}
      - POSTGRES_PASSWORD=${PASSWORD}
    ports:
      - "5430:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data

  pgadmin:
    image: dpage/pgadmin4
    environment:
      - PGADMIN_DEFAULT_EMAIL=admin@example.com
      - PGADMIN_DEFAULT_PASSWORD=admin
    ports:
      - "8080:80"
    depends_on:
      - postgres

volumes:
  postgres-data: